name: Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - run: chmod +x gradlew

      - name: Build and test
        env:
          REPOS_PAT: ${{ secrets.REPOS_PAT }}
        run: ./gradlew clean build --no-daemon

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/test-results/

      - name: Publish to Reposilite and Gitea
        if: github.ref == 'refs/heads/main'
        env:
          REPOS_PAT: ${{ secrets.REPOS_PAT }}
          GIT_USER: ${{ secrets.GIT_USER }}
          GIT_PAT: ${{ secrets.GIT_PAT }}
        run: ./gradlew publishMavenPublicationToMavenLocalRepository publishMavenPublicationToReposiliteRepository publishMavenPublicationToGiteaRepository --no-daemon

  docker:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - run: chmod +x gradlew

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: git.rokkon.com
          username: ${{ secrets.GIT_USER }}
          password: ${{ secrets.GIT_PAT }}

      - name: Build and push Docker image
        env:
          QUARKUS_CONTAINER_IMAGE_USERNAME: ${{ secrets.GIT_USER }}
          QUARKUS_CONTAINER_IMAGE_PASSWORD: ${{ secrets.GIT_PAT }}
          REPOS_PAT: ${{ secrets.REPOS_PAT }}
          GIT_USER: ${{ secrets.GIT_USER }}
          GIT_PAT: ${{ secrets.GIT_PAT }}
        run: |
          ./gradlew build -x test \
            -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.push=true \
            -Dquarkus.container-image.registry=git.rokkon.com \
            -Dquarkus.container-image.group=io-pipeline \
            -Dquarkus.container-image.additional-tags=${{ gitea.sha }} \
            --no-daemon
